package com.landleaf.ibsaas.client.meeting.model.po.meeting.mbg;

import java.io.Serializable;
import java.util.Date;

public class BookBooklist implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.id
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.username
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.createdate
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.bookdate
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Date bookdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.begintime
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.endtime
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.contactname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.contactdept
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String contactdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.contacttel
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String contacttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.contactemail
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String contactemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.numbers
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String numbers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.intro
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.roomname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String roomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.roomid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.pcname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String pcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.pcid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String pcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.projectorname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String projectorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.projectorid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String projectorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.others1
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String others1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.others2
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String others2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.cc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String cc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.specialrequire
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String specialrequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.process
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.userid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.guid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.rec
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String rec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.masterid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Integer masterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.lastupdate
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Date lastupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.updateuser
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.aid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.mgr
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String mgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.mgrtext
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String mgrtext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.attend
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String attend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.attendtext
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String attendtext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.notice
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String notice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_booklist.seq
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.id
     *
     * @return the value of book_booklist.id
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.id
     *
     * @param id the value for book_booklist.id
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.username
     *
     * @return the value of book_booklist.username
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.username
     *
     * @param username the value for book_booklist.username
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.createdate
     *
     * @return the value of book_booklist.createdate
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.createdate
     *
     * @param createdate the value for book_booklist.createdate
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.bookdate
     *
     * @return the value of book_booklist.bookdate
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Date getBookdate() {
        return bookdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.bookdate
     *
     * @param bookdate the value for book_booklist.bookdate
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setBookdate(Date bookdate) {
        this.bookdate = bookdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.begintime
     *
     * @return the value of book_booklist.begintime
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.begintime
     *
     * @param begintime the value for book_booklist.begintime
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.endtime
     *
     * @return the value of book_booklist.endtime
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.endtime
     *
     * @param endtime the value for book_booklist.endtime
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.contactname
     *
     * @return the value of book_booklist.contactname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.contactname
     *
     * @param contactname the value for book_booklist.contactname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setContactname(String contactname) {
        this.contactname = contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.contactdept
     *
     * @return the value of book_booklist.contactdept
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getContactdept() {
        return contactdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.contactdept
     *
     * @param contactdept the value for book_booklist.contactdept
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setContactdept(String contactdept) {
        this.contactdept = contactdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.contacttel
     *
     * @return the value of book_booklist.contacttel
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getContacttel() {
        return contacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.contacttel
     *
     * @param contacttel the value for book_booklist.contacttel
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setContacttel(String contacttel) {
        this.contacttel = contacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.contactemail
     *
     * @return the value of book_booklist.contactemail
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getContactemail() {
        return contactemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.contactemail
     *
     * @param contactemail the value for book_booklist.contactemail
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setContactemail(String contactemail) {
        this.contactemail = contactemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.numbers
     *
     * @return the value of book_booklist.numbers
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getNumbers() {
        return numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.numbers
     *
     * @param numbers the value for book_booklist.numbers
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setNumbers(String numbers) {
        this.numbers = numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.intro
     *
     * @return the value of book_booklist.intro
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.intro
     *
     * @param intro the value for book_booklist.intro
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.roomname
     *
     * @return the value of book_booklist.roomname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getRoomname() {
        return roomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.roomname
     *
     * @param roomname the value for book_booklist.roomname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setRoomname(String roomname) {
        this.roomname = roomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.roomid
     *
     * @return the value of book_booklist.roomid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.roomid
     *
     * @param roomid the value for book_booklist.roomid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.pcname
     *
     * @return the value of book_booklist.pcname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getPcname() {
        return pcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.pcname
     *
     * @param pcname the value for book_booklist.pcname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setPcname(String pcname) {
        this.pcname = pcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.pcid
     *
     * @return the value of book_booklist.pcid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getPcid() {
        return pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.pcid
     *
     * @param pcid the value for book_booklist.pcid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setPcid(String pcid) {
        this.pcid = pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.projectorname
     *
     * @return the value of book_booklist.projectorname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getProjectorname() {
        return projectorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.projectorname
     *
     * @param projectorname the value for book_booklist.projectorname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setProjectorname(String projectorname) {
        this.projectorname = projectorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.projectorid
     *
     * @return the value of book_booklist.projectorid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getProjectorid() {
        return projectorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.projectorid
     *
     * @param projectorid the value for book_booklist.projectorid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setProjectorid(String projectorid) {
        this.projectorid = projectorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.others1
     *
     * @return the value of book_booklist.others1
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getOthers1() {
        return others1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.others1
     *
     * @param others1 the value for book_booklist.others1
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setOthers1(String others1) {
        this.others1 = others1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.others2
     *
     * @return the value of book_booklist.others2
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getOthers2() {
        return others2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.others2
     *
     * @param others2 the value for book_booklist.others2
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setOthers2(String others2) {
        this.others2 = others2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.cc
     *
     * @return the value of book_booklist.cc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getCc() {
        return cc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.cc
     *
     * @param cc the value for book_booklist.cc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setCc(String cc) {
        this.cc = cc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.specialrequire
     *
     * @return the value of book_booklist.specialrequire
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getSpecialrequire() {
        return specialrequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.specialrequire
     *
     * @param specialrequire the value for book_booklist.specialrequire
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setSpecialrequire(String specialrequire) {
        this.specialrequire = specialrequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.process
     *
     * @return the value of book_booklist.process
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.process
     *
     * @param process the value for book_booklist.process
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setProcess(String process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.userid
     *
     * @return the value of book_booklist.userid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.userid
     *
     * @param userid the value for book_booklist.userid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.guid
     *
     * @return the value of book_booklist.guid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.guid
     *
     * @param guid the value for book_booklist.guid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.rec
     *
     * @return the value of book_booklist.rec
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getRec() {
        return rec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.rec
     *
     * @param rec the value for book_booklist.rec
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setRec(String rec) {
        this.rec = rec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.masterid
     *
     * @return the value of book_booklist.masterid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Integer getMasterid() {
        return masterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.masterid
     *
     * @param masterid the value for book_booklist.masterid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setMasterid(Integer masterid) {
        this.masterid = masterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.lastupdate
     *
     * @return the value of book_booklist.lastupdate
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.lastupdate
     *
     * @param lastupdate the value for book_booklist.lastupdate
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.updateuser
     *
     * @return the value of book_booklist.updateuser
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.updateuser
     *
     * @param updateuser the value for book_booklist.updateuser
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.aid
     *
     * @return the value of book_booklist.aid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.aid
     *
     * @param aid the value for book_booklist.aid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setAid(String aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.mgr
     *
     * @return the value of book_booklist.mgr
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getMgr() {
        return mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.mgr
     *
     * @param mgr the value for book_booklist.mgr
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setMgr(String mgr) {
        this.mgr = mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.mgrtext
     *
     * @return the value of book_booklist.mgrtext
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getMgrtext() {
        return mgrtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.mgrtext
     *
     * @param mgrtext the value for book_booklist.mgrtext
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setMgrtext(String mgrtext) {
        this.mgrtext = mgrtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.attend
     *
     * @return the value of book_booklist.attend
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getAttend() {
        return attend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.attend
     *
     * @param attend the value for book_booklist.attend
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setAttend(String attend) {
        this.attend = attend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.attendtext
     *
     * @return the value of book_booklist.attendtext
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getAttendtext() {
        return attendtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.attendtext
     *
     * @param attendtext the value for book_booklist.attendtext
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setAttendtext(String attendtext) {
        this.attendtext = attendtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.notice
     *
     * @return the value of book_booklist.notice
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.notice
     *
     * @param notice the value for book_booklist.notice
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setNotice(String notice) {
        this.notice = notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_booklist.seq
     *
     * @return the value of book_booklist.seq
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_booklist.seq
     *
     * @param seq the value for book_booklist.seq
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", createdate=").append(createdate);
        sb.append(", bookdate=").append(bookdate);
        sb.append(", begintime=").append(begintime);
        sb.append(", endtime=").append(endtime);
        sb.append(", contactname=").append(contactname);
        sb.append(", contactdept=").append(contactdept);
        sb.append(", contacttel=").append(contacttel);
        sb.append(", contactemail=").append(contactemail);
        sb.append(", numbers=").append(numbers);
        sb.append(", intro=").append(intro);
        sb.append(", roomname=").append(roomname);
        sb.append(", roomid=").append(roomid);
        sb.append(", pcname=").append(pcname);
        sb.append(", pcid=").append(pcid);
        sb.append(", projectorname=").append(projectorname);
        sb.append(", projectorid=").append(projectorid);
        sb.append(", others1=").append(others1);
        sb.append(", others2=").append(others2);
        sb.append(", cc=").append(cc);
        sb.append(", specialrequire=").append(specialrequire);
        sb.append(", process=").append(process);
        sb.append(", userid=").append(userid);
        sb.append(", guid=").append(guid);
        sb.append(", rec=").append(rec);
        sb.append(", masterid=").append(masterid);
        sb.append(", lastupdate=").append(lastupdate);
        sb.append(", updateuser=").append(updateuser);
        sb.append(", aid=").append(aid);
        sb.append(", mgr=").append(mgr);
        sb.append(", mgrtext=").append(mgrtext);
        sb.append(", attend=").append(attend);
        sb.append(", attendtext=").append(attendtext);
        sb.append(", notice=").append(notice);
        sb.append(", seq=").append(seq);
        sb.append("]");
        return sb.toString();
    }
}