package com.landleaf.ibsaas.client.meeting.model.po.meeting.mbg;

import java.util.ArrayList;
import java.util.List;

public class BookCategoriesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public BookCategoriesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCatnameIsNull() {
            addCriterion("catname is null");
            return (Criteria) this;
        }

        public Criteria andCatnameIsNotNull() {
            addCriterion("catname is not null");
            return (Criteria) this;
        }

        public Criteria andCatnameEqualTo(String value) {
            addCriterion("catname =", value, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameNotEqualTo(String value) {
            addCriterion("catname <>", value, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameGreaterThan(String value) {
            addCriterion("catname >", value, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameGreaterThanOrEqualTo(String value) {
            addCriterion("catname >=", value, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameLessThan(String value) {
            addCriterion("catname <", value, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameLessThanOrEqualTo(String value) {
            addCriterion("catname <=", value, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameLike(String value) {
            addCriterion("catname like", value, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameNotLike(String value) {
            addCriterion("catname not like", value, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameIn(List<String> values) {
            addCriterion("catname in", values, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameNotIn(List<String> values) {
            addCriterion("catname not in", values, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameBetween(String value1, String value2) {
            addCriterion("catname between", value1, value2, "catname");
            return (Criteria) this;
        }

        public Criteria andCatnameNotBetween(String value1, String value2) {
            addCriterion("catname not between", value1, value2, "catname");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderid is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("orderid =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("orderid <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("orderid >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderid >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("orderid <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("orderid <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("orderid in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("orderid not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("orderid between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderid not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andCattypeIsNull() {
            addCriterion("cattype is null");
            return (Criteria) this;
        }

        public Criteria andCattypeIsNotNull() {
            addCriterion("cattype is not null");
            return (Criteria) this;
        }

        public Criteria andCattypeEqualTo(String value) {
            addCriterion("cattype =", value, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeNotEqualTo(String value) {
            addCriterion("cattype <>", value, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeGreaterThan(String value) {
            addCriterion("cattype >", value, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeGreaterThanOrEqualTo(String value) {
            addCriterion("cattype >=", value, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeLessThan(String value) {
            addCriterion("cattype <", value, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeLessThanOrEqualTo(String value) {
            addCriterion("cattype <=", value, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeLike(String value) {
            addCriterion("cattype like", value, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeNotLike(String value) {
            addCriterion("cattype not like", value, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeIn(List<String> values) {
            addCriterion("cattype in", values, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeNotIn(List<String> values) {
            addCriterion("cattype not in", values, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeBetween(String value1, String value2) {
            addCriterion("cattype between", value1, value2, "cattype");
            return (Criteria) this;
        }

        public Criteria andCattypeNotBetween(String value1, String value2) {
            addCriterion("cattype not between", value1, value2, "cattype");
            return (Criteria) this;
        }

        public Criteria andAllowrolesIsNull() {
            addCriterion("allowroles is null");
            return (Criteria) this;
        }

        public Criteria andAllowrolesIsNotNull() {
            addCriterion("allowroles is not null");
            return (Criteria) this;
        }

        public Criteria andAllowrolesEqualTo(String value) {
            addCriterion("allowroles =", value, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesNotEqualTo(String value) {
            addCriterion("allowroles <>", value, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesGreaterThan(String value) {
            addCriterion("allowroles >", value, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesGreaterThanOrEqualTo(String value) {
            addCriterion("allowroles >=", value, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesLessThan(String value) {
            addCriterion("allowroles <", value, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesLessThanOrEqualTo(String value) {
            addCriterion("allowroles <=", value, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesLike(String value) {
            addCriterion("allowroles like", value, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesNotLike(String value) {
            addCriterion("allowroles not like", value, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesIn(List<String> values) {
            addCriterion("allowroles in", values, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesNotIn(List<String> values) {
            addCriterion("allowroles not in", values, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesBetween(String value1, String value2) {
            addCriterion("allowroles between", value1, value2, "allowroles");
            return (Criteria) this;
        }

        public Criteria andAllowrolesNotBetween(String value1, String value2) {
            addCriterion("allowroles not between", value1, value2, "allowroles");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isdelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isdelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Integer value) {
            addCriterion("isdelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Integer value) {
            addCriterion("isdelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Integer value) {
            addCriterion("isdelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("isdelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Integer value) {
            addCriterion("isdelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
            addCriterion("isdelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Integer> values) {
            addCriterion("isdelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Integer> values) {
            addCriterion("isdelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
            addCriterion("isdelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("isdelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andDomainIsNull() {
            addCriterion("domain is null");
            return (Criteria) this;
        }

        public Criteria andDomainIsNotNull() {
            addCriterion("domain is not null");
            return (Criteria) this;
        }

        public Criteria andDomainEqualTo(String value) {
            addCriterion("domain =", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotEqualTo(String value) {
            addCriterion("domain <>", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThan(String value) {
            addCriterion("domain >", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThanOrEqualTo(String value) {
            addCriterion("domain >=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThan(String value) {
            addCriterion("domain <", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThanOrEqualTo(String value) {
            addCriterion("domain <=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLike(String value) {
            addCriterion("domain like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotLike(String value) {
            addCriterion("domain not like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainIn(List<String> values) {
            addCriterion("domain in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotIn(List<String> values) {
            addCriterion("domain not in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainBetween(String value1, String value2) {
            addCriterion("domain between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotBetween(String value1, String value2) {
            addCriterion("domain not between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andHasprojectorIsNull() {
            addCriterion("hasprojector is null");
            return (Criteria) this;
        }

        public Criteria andHasprojectorIsNotNull() {
            addCriterion("hasprojector is not null");
            return (Criteria) this;
        }

        public Criteria andHasprojectorEqualTo(String value) {
            addCriterion("hasprojector =", value, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorNotEqualTo(String value) {
            addCriterion("hasprojector <>", value, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorGreaterThan(String value) {
            addCriterion("hasprojector >", value, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorGreaterThanOrEqualTo(String value) {
            addCriterion("hasprojector >=", value, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorLessThan(String value) {
            addCriterion("hasprojector <", value, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorLessThanOrEqualTo(String value) {
            addCriterion("hasprojector <=", value, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorLike(String value) {
            addCriterion("hasprojector like", value, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorNotLike(String value) {
            addCriterion("hasprojector not like", value, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorIn(List<String> values) {
            addCriterion("hasprojector in", values, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorNotIn(List<String> values) {
            addCriterion("hasprojector not in", values, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorBetween(String value1, String value2) {
            addCriterion("hasprojector between", value1, value2, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHasprojectorNotBetween(String value1, String value2) {
            addCriterion("hasprojector not between", value1, value2, "hasprojector");
            return (Criteria) this;
        }

        public Criteria andHaspcIsNull() {
            addCriterion("haspc is null");
            return (Criteria) this;
        }

        public Criteria andHaspcIsNotNull() {
            addCriterion("haspc is not null");
            return (Criteria) this;
        }

        public Criteria andHaspcEqualTo(String value) {
            addCriterion("haspc =", value, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcNotEqualTo(String value) {
            addCriterion("haspc <>", value, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcGreaterThan(String value) {
            addCriterion("haspc >", value, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcGreaterThanOrEqualTo(String value) {
            addCriterion("haspc >=", value, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcLessThan(String value) {
            addCriterion("haspc <", value, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcLessThanOrEqualTo(String value) {
            addCriterion("haspc <=", value, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcLike(String value) {
            addCriterion("haspc like", value, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcNotLike(String value) {
            addCriterion("haspc not like", value, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcIn(List<String> values) {
            addCriterion("haspc in", values, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcNotIn(List<String> values) {
            addCriterion("haspc not in", values, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcBetween(String value1, String value2) {
            addCriterion("haspc between", value1, value2, "haspc");
            return (Criteria) this;
        }

        public Criteria andHaspcNotBetween(String value1, String value2) {
            addCriterion("haspc not between", value1, value2, "haspc");
            return (Criteria) this;
        }

        public Criteria andHastcIsNull() {
            addCriterion("hastc is null");
            return (Criteria) this;
        }

        public Criteria andHastcIsNotNull() {
            addCriterion("hastc is not null");
            return (Criteria) this;
        }

        public Criteria andHastcEqualTo(String value) {
            addCriterion("hastc =", value, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcNotEqualTo(String value) {
            addCriterion("hastc <>", value, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcGreaterThan(String value) {
            addCriterion("hastc >", value, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcGreaterThanOrEqualTo(String value) {
            addCriterion("hastc >=", value, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcLessThan(String value) {
            addCriterion("hastc <", value, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcLessThanOrEqualTo(String value) {
            addCriterion("hastc <=", value, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcLike(String value) {
            addCriterion("hastc like", value, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcNotLike(String value) {
            addCriterion("hastc not like", value, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcIn(List<String> values) {
            addCriterion("hastc in", values, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcNotIn(List<String> values) {
            addCriterion("hastc not in", values, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcBetween(String value1, String value2) {
            addCriterion("hastc between", value1, value2, "hastc");
            return (Criteria) this;
        }

        public Criteria andHastcNotBetween(String value1, String value2) {
            addCriterion("hastc not between", value1, value2, "hastc");
            return (Criteria) this;
        }

        public Criteria andHasvtcIsNull() {
            addCriterion("hasvtc is null");
            return (Criteria) this;
        }

        public Criteria andHasvtcIsNotNull() {
            addCriterion("hasvtc is not null");
            return (Criteria) this;
        }

        public Criteria andHasvtcEqualTo(String value) {
            addCriterion("hasvtc =", value, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcNotEqualTo(String value) {
            addCriterion("hasvtc <>", value, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcGreaterThan(String value) {
            addCriterion("hasvtc >", value, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcGreaterThanOrEqualTo(String value) {
            addCriterion("hasvtc >=", value, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcLessThan(String value) {
            addCriterion("hasvtc <", value, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcLessThanOrEqualTo(String value) {
            addCriterion("hasvtc <=", value, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcLike(String value) {
            addCriterion("hasvtc like", value, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcNotLike(String value) {
            addCriterion("hasvtc not like", value, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcIn(List<String> values) {
            addCriterion("hasvtc in", values, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcNotIn(List<String> values) {
            addCriterion("hasvtc not in", values, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcBetween(String value1, String value2) {
            addCriterion("hasvtc between", value1, value2, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andHasvtcNotBetween(String value1, String value2) {
            addCriterion("hasvtc not between", value1, value2, "hasvtc");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumtextIsNull() {
            addCriterion("numtext is null");
            return (Criteria) this;
        }

        public Criteria andNumtextIsNotNull() {
            addCriterion("numtext is not null");
            return (Criteria) this;
        }

        public Criteria andNumtextEqualTo(String value) {
            addCriterion("numtext =", value, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextNotEqualTo(String value) {
            addCriterion("numtext <>", value, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextGreaterThan(String value) {
            addCriterion("numtext >", value, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextGreaterThanOrEqualTo(String value) {
            addCriterion("numtext >=", value, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextLessThan(String value) {
            addCriterion("numtext <", value, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextLessThanOrEqualTo(String value) {
            addCriterion("numtext <=", value, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextLike(String value) {
            addCriterion("numtext like", value, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextNotLike(String value) {
            addCriterion("numtext not like", value, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextIn(List<String> values) {
            addCriterion("numtext in", values, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextNotIn(List<String> values) {
            addCriterion("numtext not in", values, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextBetween(String value1, String value2) {
            addCriterion("numtext between", value1, value2, "numtext");
            return (Criteria) this;
        }

        public Criteria andNumtextNotBetween(String value1, String value2) {
            addCriterion("numtext not between", value1, value2, "numtext");
            return (Criteria) this;
        }

        public Criteria andFlashIsNull() {
            addCriterion("flash is null");
            return (Criteria) this;
        }

        public Criteria andFlashIsNotNull() {
            addCriterion("flash is not null");
            return (Criteria) this;
        }

        public Criteria andFlashEqualTo(String value) {
            addCriterion("flash =", value, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashNotEqualTo(String value) {
            addCriterion("flash <>", value, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashGreaterThan(String value) {
            addCriterion("flash >", value, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashGreaterThanOrEqualTo(String value) {
            addCriterion("flash >=", value, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashLessThan(String value) {
            addCriterion("flash <", value, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashLessThanOrEqualTo(String value) {
            addCriterion("flash <=", value, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashLike(String value) {
            addCriterion("flash like", value, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashNotLike(String value) {
            addCriterion("flash not like", value, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashIn(List<String> values) {
            addCriterion("flash in", values, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashNotIn(List<String> values) {
            addCriterion("flash not in", values, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashBetween(String value1, String value2) {
            addCriterion("flash between", value1, value2, "flash");
            return (Criteria) this;
        }

        public Criteria andFlashNotBetween(String value1, String value2) {
            addCriterion("flash not between", value1, value2, "flash");
            return (Criteria) this;
        }

        public Criteria andPrev1IsNull() {
            addCriterion("prev1 is null");
            return (Criteria) this;
        }

        public Criteria andPrev1IsNotNull() {
            addCriterion("prev1 is not null");
            return (Criteria) this;
        }

        public Criteria andPrev1EqualTo(String value) {
            addCriterion("prev1 =", value, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1NotEqualTo(String value) {
            addCriterion("prev1 <>", value, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1GreaterThan(String value) {
            addCriterion("prev1 >", value, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1GreaterThanOrEqualTo(String value) {
            addCriterion("prev1 >=", value, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1LessThan(String value) {
            addCriterion("prev1 <", value, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1LessThanOrEqualTo(String value) {
            addCriterion("prev1 <=", value, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1Like(String value) {
            addCriterion("prev1 like", value, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1NotLike(String value) {
            addCriterion("prev1 not like", value, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1In(List<String> values) {
            addCriterion("prev1 in", values, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1NotIn(List<String> values) {
            addCriterion("prev1 not in", values, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1Between(String value1, String value2) {
            addCriterion("prev1 between", value1, value2, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev1NotBetween(String value1, String value2) {
            addCriterion("prev1 not between", value1, value2, "prev1");
            return (Criteria) this;
        }

        public Criteria andPrev2IsNull() {
            addCriterion("prev2 is null");
            return (Criteria) this;
        }

        public Criteria andPrev2IsNotNull() {
            addCriterion("prev2 is not null");
            return (Criteria) this;
        }

        public Criteria andPrev2EqualTo(String value) {
            addCriterion("prev2 =", value, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2NotEqualTo(String value) {
            addCriterion("prev2 <>", value, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2GreaterThan(String value) {
            addCriterion("prev2 >", value, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2GreaterThanOrEqualTo(String value) {
            addCriterion("prev2 >=", value, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2LessThan(String value) {
            addCriterion("prev2 <", value, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2LessThanOrEqualTo(String value) {
            addCriterion("prev2 <=", value, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2Like(String value) {
            addCriterion("prev2 like", value, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2NotLike(String value) {
            addCriterion("prev2 not like", value, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2In(List<String> values) {
            addCriterion("prev2 in", values, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2NotIn(List<String> values) {
            addCriterion("prev2 not in", values, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2Between(String value1, String value2) {
            addCriterion("prev2 between", value1, value2, "prev2");
            return (Criteria) this;
        }

        public Criteria andPrev2NotBetween(String value1, String value2) {
            addCriterion("prev2 not between", value1, value2, "prev2");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNull() {
            addCriterion("areaid is null");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNotNull() {
            addCriterion("areaid is not null");
            return (Criteria) this;
        }

        public Criteria andAreaidEqualTo(Integer value) {
            addCriterion("areaid =", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotEqualTo(Integer value) {
            addCriterion("areaid <>", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThan(Integer value) {
            addCriterion("areaid >", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("areaid >=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThan(Integer value) {
            addCriterion("areaid <", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThanOrEqualTo(Integer value) {
            addCriterion("areaid <=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidIn(List<Integer> values) {
            addCriterion("areaid in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotIn(List<Integer> values) {
            addCriterion("areaid not in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidBetween(Integer value1, Integer value2) {
            addCriterion("areaid between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotBetween(Integer value1, Integer value2) {
            addCriterion("areaid not between", value1, value2, "areaid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_categories
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 18 14:12:28 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}