package com.landleaf.ibsaas.client.meeting.model.po.meeting.mbg;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BookBooklistExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public BookBooklistExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andBookdateIsNull() {
            addCriterion("bookdate is null");
            return (Criteria) this;
        }

        public Criteria andBookdateIsNotNull() {
            addCriterion("bookdate is not null");
            return (Criteria) this;
        }

        public Criteria andBookdateEqualTo(Date value) {
            addCriterion("bookdate =", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateNotEqualTo(Date value) {
            addCriterion("bookdate <>", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateGreaterThan(Date value) {
            addCriterion("bookdate >", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateGreaterThanOrEqualTo(Date value) {
            addCriterion("bookdate >=", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateLessThan(Date value) {
            addCriterion("bookdate <", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateLessThanOrEqualTo(Date value) {
            addCriterion("bookdate <=", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateIn(List<Date> values) {
            addCriterion("bookdate in", values, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateNotIn(List<Date> values) {
            addCriterion("bookdate not in", values, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateBetween(Date value1, Date value2) {
            addCriterion("bookdate between", value1, value2, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateNotBetween(Date value1, Date value2) {
            addCriterion("bookdate not between", value1, value2, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBegintimeIsNull() {
            addCriterion("begintime is null");
            return (Criteria) this;
        }

        public Criteria andBegintimeIsNotNull() {
            addCriterion("begintime is not null");
            return (Criteria) this;
        }

        public Criteria andBegintimeEqualTo(Date value) {
            addCriterion("begintime =", value, "begintime");
            return (Criteria) this;
        }

        public Criteria andBegintimeNotEqualTo(Date value) {
            addCriterion("begintime <>", value, "begintime");
            return (Criteria) this;
        }

        public Criteria andBegintimeGreaterThan(Date value) {
            addCriterion("begintime >", value, "begintime");
            return (Criteria) this;
        }

        public Criteria andBegintimeGreaterThanOrEqualTo(Date value) {
            addCriterion("begintime >=", value, "begintime");
            return (Criteria) this;
        }

        public Criteria andBegintimeLessThan(Date value) {
            addCriterion("begintime <", value, "begintime");
            return (Criteria) this;
        }

        public Criteria andBegintimeLessThanOrEqualTo(Date value) {
            addCriterion("begintime <=", value, "begintime");
            return (Criteria) this;
        }

        public Criteria andBegintimeIn(List<Date> values) {
            addCriterion("begintime in", values, "begintime");
            return (Criteria) this;
        }

        public Criteria andBegintimeNotIn(List<Date> values) {
            addCriterion("begintime not in", values, "begintime");
            return (Criteria) this;
        }

        public Criteria andBegintimeBetween(Date value1, Date value2) {
            addCriterion("begintime between", value1, value2, "begintime");
            return (Criteria) this;
        }

        public Criteria andBegintimeNotBetween(Date value1, Date value2) {
            addCriterion("begintime not between", value1, value2, "begintime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endtime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endtime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endtime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endtime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endtime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endtime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endtime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endtime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endtime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endtime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endtime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endtime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andContactnameIsNull() {
            addCriterion("contactname is null");
            return (Criteria) this;
        }

        public Criteria andContactnameIsNotNull() {
            addCriterion("contactname is not null");
            return (Criteria) this;
        }

        public Criteria andContactnameEqualTo(String value) {
            addCriterion("contactname =", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameNotEqualTo(String value) {
            addCriterion("contactname <>", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameGreaterThan(String value) {
            addCriterion("contactname >", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameGreaterThanOrEqualTo(String value) {
            addCriterion("contactname >=", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameLessThan(String value) {
            addCriterion("contactname <", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameLessThanOrEqualTo(String value) {
            addCriterion("contactname <=", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameLike(String value) {
            addCriterion("contactname like", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameNotLike(String value) {
            addCriterion("contactname not like", value, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameIn(List<String> values) {
            addCriterion("contactname in", values, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameNotIn(List<String> values) {
            addCriterion("contactname not in", values, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameBetween(String value1, String value2) {
            addCriterion("contactname between", value1, value2, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactnameNotBetween(String value1, String value2) {
            addCriterion("contactname not between", value1, value2, "contactname");
            return (Criteria) this;
        }

        public Criteria andContactdeptIsNull() {
            addCriterion("contactdept is null");
            return (Criteria) this;
        }

        public Criteria andContactdeptIsNotNull() {
            addCriterion("contactdept is not null");
            return (Criteria) this;
        }

        public Criteria andContactdeptEqualTo(String value) {
            addCriterion("contactdept =", value, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptNotEqualTo(String value) {
            addCriterion("contactdept <>", value, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptGreaterThan(String value) {
            addCriterion("contactdept >", value, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptGreaterThanOrEqualTo(String value) {
            addCriterion("contactdept >=", value, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptLessThan(String value) {
            addCriterion("contactdept <", value, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptLessThanOrEqualTo(String value) {
            addCriterion("contactdept <=", value, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptLike(String value) {
            addCriterion("contactdept like", value, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptNotLike(String value) {
            addCriterion("contactdept not like", value, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptIn(List<String> values) {
            addCriterion("contactdept in", values, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptNotIn(List<String> values) {
            addCriterion("contactdept not in", values, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptBetween(String value1, String value2) {
            addCriterion("contactdept between", value1, value2, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContactdeptNotBetween(String value1, String value2) {
            addCriterion("contactdept not between", value1, value2, "contactdept");
            return (Criteria) this;
        }

        public Criteria andContacttelIsNull() {
            addCriterion("contacttel is null");
            return (Criteria) this;
        }

        public Criteria andContacttelIsNotNull() {
            addCriterion("contacttel is not null");
            return (Criteria) this;
        }

        public Criteria andContacttelEqualTo(String value) {
            addCriterion("contacttel =", value, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelNotEqualTo(String value) {
            addCriterion("contacttel <>", value, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelGreaterThan(String value) {
            addCriterion("contacttel >", value, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelGreaterThanOrEqualTo(String value) {
            addCriterion("contacttel >=", value, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelLessThan(String value) {
            addCriterion("contacttel <", value, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelLessThanOrEqualTo(String value) {
            addCriterion("contacttel <=", value, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelLike(String value) {
            addCriterion("contacttel like", value, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelNotLike(String value) {
            addCriterion("contacttel not like", value, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelIn(List<String> values) {
            addCriterion("contacttel in", values, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelNotIn(List<String> values) {
            addCriterion("contacttel not in", values, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelBetween(String value1, String value2) {
            addCriterion("contacttel between", value1, value2, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContacttelNotBetween(String value1, String value2) {
            addCriterion("contacttel not between", value1, value2, "contacttel");
            return (Criteria) this;
        }

        public Criteria andContactemailIsNull() {
            addCriterion("contactemail is null");
            return (Criteria) this;
        }

        public Criteria andContactemailIsNotNull() {
            addCriterion("contactemail is not null");
            return (Criteria) this;
        }

        public Criteria andContactemailEqualTo(String value) {
            addCriterion("contactemail =", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailNotEqualTo(String value) {
            addCriterion("contactemail <>", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailGreaterThan(String value) {
            addCriterion("contactemail >", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailGreaterThanOrEqualTo(String value) {
            addCriterion("contactemail >=", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailLessThan(String value) {
            addCriterion("contactemail <", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailLessThanOrEqualTo(String value) {
            addCriterion("contactemail <=", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailLike(String value) {
            addCriterion("contactemail like", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailNotLike(String value) {
            addCriterion("contactemail not like", value, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailIn(List<String> values) {
            addCriterion("contactemail in", values, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailNotIn(List<String> values) {
            addCriterion("contactemail not in", values, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailBetween(String value1, String value2) {
            addCriterion("contactemail between", value1, value2, "contactemail");
            return (Criteria) this;
        }

        public Criteria andContactemailNotBetween(String value1, String value2) {
            addCriterion("contactemail not between", value1, value2, "contactemail");
            return (Criteria) this;
        }

        public Criteria andNumbersIsNull() {
            addCriterion("numbers is null");
            return (Criteria) this;
        }

        public Criteria andNumbersIsNotNull() {
            addCriterion("numbers is not null");
            return (Criteria) this;
        }

        public Criteria andNumbersEqualTo(String value) {
            addCriterion("numbers =", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersNotEqualTo(String value) {
            addCriterion("numbers <>", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersGreaterThan(String value) {
            addCriterion("numbers >", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersGreaterThanOrEqualTo(String value) {
            addCriterion("numbers >=", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersLessThan(String value) {
            addCriterion("numbers <", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersLessThanOrEqualTo(String value) {
            addCriterion("numbers <=", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersLike(String value) {
            addCriterion("numbers like", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersNotLike(String value) {
            addCriterion("numbers not like", value, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersIn(List<String> values) {
            addCriterion("numbers in", values, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersNotIn(List<String> values) {
            addCriterion("numbers not in", values, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersBetween(String value1, String value2) {
            addCriterion("numbers between", value1, value2, "numbers");
            return (Criteria) this;
        }

        public Criteria andNumbersNotBetween(String value1, String value2) {
            addCriterion("numbers not between", value1, value2, "numbers");
            return (Criteria) this;
        }

        public Criteria andIntroIsNull() {
            addCriterion("intro is null");
            return (Criteria) this;
        }

        public Criteria andIntroIsNotNull() {
            addCriterion("intro is not null");
            return (Criteria) this;
        }

        public Criteria andIntroEqualTo(String value) {
            addCriterion("intro =", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotEqualTo(String value) {
            addCriterion("intro <>", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThan(String value) {
            addCriterion("intro >", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThanOrEqualTo(String value) {
            addCriterion("intro >=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThan(String value) {
            addCriterion("intro <", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThanOrEqualTo(String value) {
            addCriterion("intro <=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLike(String value) {
            addCriterion("intro like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotLike(String value) {
            addCriterion("intro not like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroIn(List<String> values) {
            addCriterion("intro in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotIn(List<String> values) {
            addCriterion("intro not in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroBetween(String value1, String value2) {
            addCriterion("intro between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotBetween(String value1, String value2) {
            addCriterion("intro not between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andRoomnameIsNull() {
            addCriterion("roomname is null");
            return (Criteria) this;
        }

        public Criteria andRoomnameIsNotNull() {
            addCriterion("roomname is not null");
            return (Criteria) this;
        }

        public Criteria andRoomnameEqualTo(String value) {
            addCriterion("roomname =", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameNotEqualTo(String value) {
            addCriterion("roomname <>", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameGreaterThan(String value) {
            addCriterion("roomname >", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameGreaterThanOrEqualTo(String value) {
            addCriterion("roomname >=", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameLessThan(String value) {
            addCriterion("roomname <", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameLessThanOrEqualTo(String value) {
            addCriterion("roomname <=", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameLike(String value) {
            addCriterion("roomname like", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameNotLike(String value) {
            addCriterion("roomname not like", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameIn(List<String> values) {
            addCriterion("roomname in", values, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameNotIn(List<String> values) {
            addCriterion("roomname not in", values, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameBetween(String value1, String value2) {
            addCriterion("roomname between", value1, value2, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameNotBetween(String value1, String value2) {
            addCriterion("roomname not between", value1, value2, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomidIsNull() {
            addCriterion("roomid is null");
            return (Criteria) this;
        }

        public Criteria andRoomidIsNotNull() {
            addCriterion("roomid is not null");
            return (Criteria) this;
        }

        public Criteria andRoomidEqualTo(String value) {
            addCriterion("roomid =", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotEqualTo(String value) {
            addCriterion("roomid <>", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThan(String value) {
            addCriterion("roomid >", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThanOrEqualTo(String value) {
            addCriterion("roomid >=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThan(String value) {
            addCriterion("roomid <", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThanOrEqualTo(String value) {
            addCriterion("roomid <=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLike(String value) {
            addCriterion("roomid like", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotLike(String value) {
            addCriterion("roomid not like", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidIn(List<String> values) {
            addCriterion("roomid in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotIn(List<String> values) {
            addCriterion("roomid not in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidBetween(String value1, String value2) {
            addCriterion("roomid between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotBetween(String value1, String value2) {
            addCriterion("roomid not between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andPcnameIsNull() {
            addCriterion("pcname is null");
            return (Criteria) this;
        }

        public Criteria andPcnameIsNotNull() {
            addCriterion("pcname is not null");
            return (Criteria) this;
        }

        public Criteria andPcnameEqualTo(String value) {
            addCriterion("pcname =", value, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameNotEqualTo(String value) {
            addCriterion("pcname <>", value, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameGreaterThan(String value) {
            addCriterion("pcname >", value, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameGreaterThanOrEqualTo(String value) {
            addCriterion("pcname >=", value, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameLessThan(String value) {
            addCriterion("pcname <", value, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameLessThanOrEqualTo(String value) {
            addCriterion("pcname <=", value, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameLike(String value) {
            addCriterion("pcname like", value, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameNotLike(String value) {
            addCriterion("pcname not like", value, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameIn(List<String> values) {
            addCriterion("pcname in", values, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameNotIn(List<String> values) {
            addCriterion("pcname not in", values, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameBetween(String value1, String value2) {
            addCriterion("pcname between", value1, value2, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcnameNotBetween(String value1, String value2) {
            addCriterion("pcname not between", value1, value2, "pcname");
            return (Criteria) this;
        }

        public Criteria andPcidIsNull() {
            addCriterion("pcid is null");
            return (Criteria) this;
        }

        public Criteria andPcidIsNotNull() {
            addCriterion("pcid is not null");
            return (Criteria) this;
        }

        public Criteria andPcidEqualTo(String value) {
            addCriterion("pcid =", value, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidNotEqualTo(String value) {
            addCriterion("pcid <>", value, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidGreaterThan(String value) {
            addCriterion("pcid >", value, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidGreaterThanOrEqualTo(String value) {
            addCriterion("pcid >=", value, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidLessThan(String value) {
            addCriterion("pcid <", value, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidLessThanOrEqualTo(String value) {
            addCriterion("pcid <=", value, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidLike(String value) {
            addCriterion("pcid like", value, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidNotLike(String value) {
            addCriterion("pcid not like", value, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidIn(List<String> values) {
            addCriterion("pcid in", values, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidNotIn(List<String> values) {
            addCriterion("pcid not in", values, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidBetween(String value1, String value2) {
            addCriterion("pcid between", value1, value2, "pcid");
            return (Criteria) this;
        }

        public Criteria andPcidNotBetween(String value1, String value2) {
            addCriterion("pcid not between", value1, value2, "pcid");
            return (Criteria) this;
        }

        public Criteria andProjectornameIsNull() {
            addCriterion("projectorname is null");
            return (Criteria) this;
        }

        public Criteria andProjectornameIsNotNull() {
            addCriterion("projectorname is not null");
            return (Criteria) this;
        }

        public Criteria andProjectornameEqualTo(String value) {
            addCriterion("projectorname =", value, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameNotEqualTo(String value) {
            addCriterion("projectorname <>", value, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameGreaterThan(String value) {
            addCriterion("projectorname >", value, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameGreaterThanOrEqualTo(String value) {
            addCriterion("projectorname >=", value, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameLessThan(String value) {
            addCriterion("projectorname <", value, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameLessThanOrEqualTo(String value) {
            addCriterion("projectorname <=", value, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameLike(String value) {
            addCriterion("projectorname like", value, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameNotLike(String value) {
            addCriterion("projectorname not like", value, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameIn(List<String> values) {
            addCriterion("projectorname in", values, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameNotIn(List<String> values) {
            addCriterion("projectorname not in", values, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameBetween(String value1, String value2) {
            addCriterion("projectorname between", value1, value2, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectornameNotBetween(String value1, String value2) {
            addCriterion("projectorname not between", value1, value2, "projectorname");
            return (Criteria) this;
        }

        public Criteria andProjectoridIsNull() {
            addCriterion("projectorid is null");
            return (Criteria) this;
        }

        public Criteria andProjectoridIsNotNull() {
            addCriterion("projectorid is not null");
            return (Criteria) this;
        }

        public Criteria andProjectoridEqualTo(String value) {
            addCriterion("projectorid =", value, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridNotEqualTo(String value) {
            addCriterion("projectorid <>", value, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridGreaterThan(String value) {
            addCriterion("projectorid >", value, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridGreaterThanOrEqualTo(String value) {
            addCriterion("projectorid >=", value, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridLessThan(String value) {
            addCriterion("projectorid <", value, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridLessThanOrEqualTo(String value) {
            addCriterion("projectorid <=", value, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridLike(String value) {
            addCriterion("projectorid like", value, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridNotLike(String value) {
            addCriterion("projectorid not like", value, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridIn(List<String> values) {
            addCriterion("projectorid in", values, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridNotIn(List<String> values) {
            addCriterion("projectorid not in", values, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridBetween(String value1, String value2) {
            addCriterion("projectorid between", value1, value2, "projectorid");
            return (Criteria) this;
        }

        public Criteria andProjectoridNotBetween(String value1, String value2) {
            addCriterion("projectorid not between", value1, value2, "projectorid");
            return (Criteria) this;
        }

        public Criteria andOthers1IsNull() {
            addCriterion("others1 is null");
            return (Criteria) this;
        }

        public Criteria andOthers1IsNotNull() {
            addCriterion("others1 is not null");
            return (Criteria) this;
        }

        public Criteria andOthers1EqualTo(String value) {
            addCriterion("others1 =", value, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1NotEqualTo(String value) {
            addCriterion("others1 <>", value, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1GreaterThan(String value) {
            addCriterion("others1 >", value, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1GreaterThanOrEqualTo(String value) {
            addCriterion("others1 >=", value, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1LessThan(String value) {
            addCriterion("others1 <", value, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1LessThanOrEqualTo(String value) {
            addCriterion("others1 <=", value, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1Like(String value) {
            addCriterion("others1 like", value, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1NotLike(String value) {
            addCriterion("others1 not like", value, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1In(List<String> values) {
            addCriterion("others1 in", values, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1NotIn(List<String> values) {
            addCriterion("others1 not in", values, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1Between(String value1, String value2) {
            addCriterion("others1 between", value1, value2, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers1NotBetween(String value1, String value2) {
            addCriterion("others1 not between", value1, value2, "others1");
            return (Criteria) this;
        }

        public Criteria andOthers2IsNull() {
            addCriterion("others2 is null");
            return (Criteria) this;
        }

        public Criteria andOthers2IsNotNull() {
            addCriterion("others2 is not null");
            return (Criteria) this;
        }

        public Criteria andOthers2EqualTo(String value) {
            addCriterion("others2 =", value, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2NotEqualTo(String value) {
            addCriterion("others2 <>", value, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2GreaterThan(String value) {
            addCriterion("others2 >", value, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2GreaterThanOrEqualTo(String value) {
            addCriterion("others2 >=", value, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2LessThan(String value) {
            addCriterion("others2 <", value, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2LessThanOrEqualTo(String value) {
            addCriterion("others2 <=", value, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2Like(String value) {
            addCriterion("others2 like", value, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2NotLike(String value) {
            addCriterion("others2 not like", value, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2In(List<String> values) {
            addCriterion("others2 in", values, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2NotIn(List<String> values) {
            addCriterion("others2 not in", values, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2Between(String value1, String value2) {
            addCriterion("others2 between", value1, value2, "others2");
            return (Criteria) this;
        }

        public Criteria andOthers2NotBetween(String value1, String value2) {
            addCriterion("others2 not between", value1, value2, "others2");
            return (Criteria) this;
        }

        public Criteria andCcIsNull() {
            addCriterion("cc is null");
            return (Criteria) this;
        }

        public Criteria andCcIsNotNull() {
            addCriterion("cc is not null");
            return (Criteria) this;
        }

        public Criteria andCcEqualTo(String value) {
            addCriterion("cc =", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcNotEqualTo(String value) {
            addCriterion("cc <>", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcGreaterThan(String value) {
            addCriterion("cc >", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcGreaterThanOrEqualTo(String value) {
            addCriterion("cc >=", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcLessThan(String value) {
            addCriterion("cc <", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcLessThanOrEqualTo(String value) {
            addCriterion("cc <=", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcLike(String value) {
            addCriterion("cc like", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcNotLike(String value) {
            addCriterion("cc not like", value, "cc");
            return (Criteria) this;
        }

        public Criteria andCcIn(List<String> values) {
            addCriterion("cc in", values, "cc");
            return (Criteria) this;
        }

        public Criteria andCcNotIn(List<String> values) {
            addCriterion("cc not in", values, "cc");
            return (Criteria) this;
        }

        public Criteria andCcBetween(String value1, String value2) {
            addCriterion("cc between", value1, value2, "cc");
            return (Criteria) this;
        }

        public Criteria andCcNotBetween(String value1, String value2) {
            addCriterion("cc not between", value1, value2, "cc");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireIsNull() {
            addCriterion("specialrequire is null");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireIsNotNull() {
            addCriterion("specialrequire is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireEqualTo(String value) {
            addCriterion("specialrequire =", value, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireNotEqualTo(String value) {
            addCriterion("specialrequire <>", value, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireGreaterThan(String value) {
            addCriterion("specialrequire >", value, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireGreaterThanOrEqualTo(String value) {
            addCriterion("specialrequire >=", value, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireLessThan(String value) {
            addCriterion("specialrequire <", value, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireLessThanOrEqualTo(String value) {
            addCriterion("specialrequire <=", value, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireLike(String value) {
            addCriterion("specialrequire like", value, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireNotLike(String value) {
            addCriterion("specialrequire not like", value, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireIn(List<String> values) {
            addCriterion("specialrequire in", values, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireNotIn(List<String> values) {
            addCriterion("specialrequire not in", values, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireBetween(String value1, String value2) {
            addCriterion("specialrequire between", value1, value2, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andSpecialrequireNotBetween(String value1, String value2) {
            addCriterion("specialrequire not between", value1, value2, "specialrequire");
            return (Criteria) this;
        }

        public Criteria andProcessIsNull() {
            addCriterion("process is null");
            return (Criteria) this;
        }

        public Criteria andProcessIsNotNull() {
            addCriterion("process is not null");
            return (Criteria) this;
        }

        public Criteria andProcessEqualTo(String value) {
            addCriterion("process =", value, "process");
            return (Criteria) this;
        }

        public Criteria andProcessNotEqualTo(String value) {
            addCriterion("process <>", value, "process");
            return (Criteria) this;
        }

        public Criteria andProcessGreaterThan(String value) {
            addCriterion("process >", value, "process");
            return (Criteria) this;
        }

        public Criteria andProcessGreaterThanOrEqualTo(String value) {
            addCriterion("process >=", value, "process");
            return (Criteria) this;
        }

        public Criteria andProcessLessThan(String value) {
            addCriterion("process <", value, "process");
            return (Criteria) this;
        }

        public Criteria andProcessLessThanOrEqualTo(String value) {
            addCriterion("process <=", value, "process");
            return (Criteria) this;
        }

        public Criteria andProcessLike(String value) {
            addCriterion("process like", value, "process");
            return (Criteria) this;
        }

        public Criteria andProcessNotLike(String value) {
            addCriterion("process not like", value, "process");
            return (Criteria) this;
        }

        public Criteria andProcessIn(List<String> values) {
            addCriterion("process in", values, "process");
            return (Criteria) this;
        }

        public Criteria andProcessNotIn(List<String> values) {
            addCriterion("process not in", values, "process");
            return (Criteria) this;
        }

        public Criteria andProcessBetween(String value1, String value2) {
            addCriterion("process between", value1, value2, "process");
            return (Criteria) this;
        }

        public Criteria andProcessNotBetween(String value1, String value2) {
            addCriterion("process not between", value1, value2, "process");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userid like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userid not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andGuidIsNull() {
            addCriterion("guid is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("guid is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("guid =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("guid <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("guid >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("guid >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("guid <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("guid <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("guid like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("guid not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("guid in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("guid not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("guid between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("guid not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andRecIsNull() {
            addCriterion("rec is null");
            return (Criteria) this;
        }

        public Criteria andRecIsNotNull() {
            addCriterion("rec is not null");
            return (Criteria) this;
        }

        public Criteria andRecEqualTo(String value) {
            addCriterion("rec =", value, "rec");
            return (Criteria) this;
        }

        public Criteria andRecNotEqualTo(String value) {
            addCriterion("rec <>", value, "rec");
            return (Criteria) this;
        }

        public Criteria andRecGreaterThan(String value) {
            addCriterion("rec >", value, "rec");
            return (Criteria) this;
        }

        public Criteria andRecGreaterThanOrEqualTo(String value) {
            addCriterion("rec >=", value, "rec");
            return (Criteria) this;
        }

        public Criteria andRecLessThan(String value) {
            addCriterion("rec <", value, "rec");
            return (Criteria) this;
        }

        public Criteria andRecLessThanOrEqualTo(String value) {
            addCriterion("rec <=", value, "rec");
            return (Criteria) this;
        }

        public Criteria andRecLike(String value) {
            addCriterion("rec like", value, "rec");
            return (Criteria) this;
        }

        public Criteria andRecNotLike(String value) {
            addCriterion("rec not like", value, "rec");
            return (Criteria) this;
        }

        public Criteria andRecIn(List<String> values) {
            addCriterion("rec in", values, "rec");
            return (Criteria) this;
        }

        public Criteria andRecNotIn(List<String> values) {
            addCriterion("rec not in", values, "rec");
            return (Criteria) this;
        }

        public Criteria andRecBetween(String value1, String value2) {
            addCriterion("rec between", value1, value2, "rec");
            return (Criteria) this;
        }

        public Criteria andRecNotBetween(String value1, String value2) {
            addCriterion("rec not between", value1, value2, "rec");
            return (Criteria) this;
        }

        public Criteria andMasteridIsNull() {
            addCriterion("masterid is null");
            return (Criteria) this;
        }

        public Criteria andMasteridIsNotNull() {
            addCriterion("masterid is not null");
            return (Criteria) this;
        }

        public Criteria andMasteridEqualTo(Integer value) {
            addCriterion("masterid =", value, "masterid");
            return (Criteria) this;
        }

        public Criteria andMasteridNotEqualTo(Integer value) {
            addCriterion("masterid <>", value, "masterid");
            return (Criteria) this;
        }

        public Criteria andMasteridGreaterThan(Integer value) {
            addCriterion("masterid >", value, "masterid");
            return (Criteria) this;
        }

        public Criteria andMasteridGreaterThanOrEqualTo(Integer value) {
            addCriterion("masterid >=", value, "masterid");
            return (Criteria) this;
        }

        public Criteria andMasteridLessThan(Integer value) {
            addCriterion("masterid <", value, "masterid");
            return (Criteria) this;
        }

        public Criteria andMasteridLessThanOrEqualTo(Integer value) {
            addCriterion("masterid <=", value, "masterid");
            return (Criteria) this;
        }

        public Criteria andMasteridIn(List<Integer> values) {
            addCriterion("masterid in", values, "masterid");
            return (Criteria) this;
        }

        public Criteria andMasteridNotIn(List<Integer> values) {
            addCriterion("masterid not in", values, "masterid");
            return (Criteria) this;
        }

        public Criteria andMasteridBetween(Integer value1, Integer value2) {
            addCriterion("masterid between", value1, value2, "masterid");
            return (Criteria) this;
        }

        public Criteria andMasteridNotBetween(Integer value1, Integer value2) {
            addCriterion("masterid not between", value1, value2, "masterid");
            return (Criteria) this;
        }

        public Criteria andLastupdateIsNull() {
            addCriterion("lastupdate is null");
            return (Criteria) this;
        }

        public Criteria andLastupdateIsNotNull() {
            addCriterion("lastupdate is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdateEqualTo(Date value) {
            addCriterion("lastupdate =", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateNotEqualTo(Date value) {
            addCriterion("lastupdate <>", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateGreaterThan(Date value) {
            addCriterion("lastupdate >", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastupdate >=", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateLessThan(Date value) {
            addCriterion("lastupdate <", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateLessThanOrEqualTo(Date value) {
            addCriterion("lastupdate <=", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateIn(List<Date> values) {
            addCriterion("lastupdate in", values, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateNotIn(List<Date> values) {
            addCriterion("lastupdate not in", values, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateBetween(Date value1, Date value2) {
            addCriterion("lastupdate between", value1, value2, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateNotBetween(Date value1, Date value2) {
            addCriterion("lastupdate not between", value1, value2, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNull() {
            addCriterion("updateuser is null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNotNull() {
            addCriterion("updateuser is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserEqualTo(String value) {
            addCriterion("updateuser =", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotEqualTo(String value) {
            addCriterion("updateuser <>", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThan(String value) {
            addCriterion("updateuser >", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("updateuser >=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThan(String value) {
            addCriterion("updateuser <", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThanOrEqualTo(String value) {
            addCriterion("updateuser <=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLike(String value) {
            addCriterion("updateuser like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotLike(String value) {
            addCriterion("updateuser not like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIn(List<String> values) {
            addCriterion("updateuser in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotIn(List<String> values) {
            addCriterion("updateuser not in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserBetween(String value1, String value2) {
            addCriterion("updateuser between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotBetween(String value1, String value2) {
            addCriterion("updateuser not between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andAidIsNull() {
            addCriterion("aid is null");
            return (Criteria) this;
        }

        public Criteria andAidIsNotNull() {
            addCriterion("aid is not null");
            return (Criteria) this;
        }

        public Criteria andAidEqualTo(String value) {
            addCriterion("aid =", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotEqualTo(String value) {
            addCriterion("aid <>", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThan(String value) {
            addCriterion("aid >", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThanOrEqualTo(String value) {
            addCriterion("aid >=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThan(String value) {
            addCriterion("aid <", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThanOrEqualTo(String value) {
            addCriterion("aid <=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLike(String value) {
            addCriterion("aid like", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotLike(String value) {
            addCriterion("aid not like", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidIn(List<String> values) {
            addCriterion("aid in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotIn(List<String> values) {
            addCriterion("aid not in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidBetween(String value1, String value2) {
            addCriterion("aid between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotBetween(String value1, String value2) {
            addCriterion("aid not between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andMgrIsNull() {
            addCriterion("mgr is null");
            return (Criteria) this;
        }

        public Criteria andMgrIsNotNull() {
            addCriterion("mgr is not null");
            return (Criteria) this;
        }

        public Criteria andMgrEqualTo(String value) {
            addCriterion("mgr =", value, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrNotEqualTo(String value) {
            addCriterion("mgr <>", value, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrGreaterThan(String value) {
            addCriterion("mgr >", value, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrGreaterThanOrEqualTo(String value) {
            addCriterion("mgr >=", value, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrLessThan(String value) {
            addCriterion("mgr <", value, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrLessThanOrEqualTo(String value) {
            addCriterion("mgr <=", value, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrLike(String value) {
            addCriterion("mgr like", value, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrNotLike(String value) {
            addCriterion("mgr not like", value, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrIn(List<String> values) {
            addCriterion("mgr in", values, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrNotIn(List<String> values) {
            addCriterion("mgr not in", values, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrBetween(String value1, String value2) {
            addCriterion("mgr between", value1, value2, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrNotBetween(String value1, String value2) {
            addCriterion("mgr not between", value1, value2, "mgr");
            return (Criteria) this;
        }

        public Criteria andMgrtextIsNull() {
            addCriterion("mgrtext is null");
            return (Criteria) this;
        }

        public Criteria andMgrtextIsNotNull() {
            addCriterion("mgrtext is not null");
            return (Criteria) this;
        }

        public Criteria andMgrtextEqualTo(String value) {
            addCriterion("mgrtext =", value, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextNotEqualTo(String value) {
            addCriterion("mgrtext <>", value, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextGreaterThan(String value) {
            addCriterion("mgrtext >", value, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextGreaterThanOrEqualTo(String value) {
            addCriterion("mgrtext >=", value, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextLessThan(String value) {
            addCriterion("mgrtext <", value, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextLessThanOrEqualTo(String value) {
            addCriterion("mgrtext <=", value, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextLike(String value) {
            addCriterion("mgrtext like", value, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextNotLike(String value) {
            addCriterion("mgrtext not like", value, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextIn(List<String> values) {
            addCriterion("mgrtext in", values, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextNotIn(List<String> values) {
            addCriterion("mgrtext not in", values, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextBetween(String value1, String value2) {
            addCriterion("mgrtext between", value1, value2, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andMgrtextNotBetween(String value1, String value2) {
            addCriterion("mgrtext not between", value1, value2, "mgrtext");
            return (Criteria) this;
        }

        public Criteria andAttendIsNull() {
            addCriterion("attend is null");
            return (Criteria) this;
        }

        public Criteria andAttendIsNotNull() {
            addCriterion("attend is not null");
            return (Criteria) this;
        }

        public Criteria andAttendEqualTo(String value) {
            addCriterion("attend =", value, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendNotEqualTo(String value) {
            addCriterion("attend <>", value, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendGreaterThan(String value) {
            addCriterion("attend >", value, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendGreaterThanOrEqualTo(String value) {
            addCriterion("attend >=", value, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendLessThan(String value) {
            addCriterion("attend <", value, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendLessThanOrEqualTo(String value) {
            addCriterion("attend <=", value, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendLike(String value) {
            addCriterion("attend like", value, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendNotLike(String value) {
            addCriterion("attend not like", value, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendIn(List<String> values) {
            addCriterion("attend in", values, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendNotIn(List<String> values) {
            addCriterion("attend not in", values, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendBetween(String value1, String value2) {
            addCriterion("attend between", value1, value2, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendNotBetween(String value1, String value2) {
            addCriterion("attend not between", value1, value2, "attend");
            return (Criteria) this;
        }

        public Criteria andAttendtextIsNull() {
            addCriterion("attendtext is null");
            return (Criteria) this;
        }

        public Criteria andAttendtextIsNotNull() {
            addCriterion("attendtext is not null");
            return (Criteria) this;
        }

        public Criteria andAttendtextEqualTo(String value) {
            addCriterion("attendtext =", value, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextNotEqualTo(String value) {
            addCriterion("attendtext <>", value, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextGreaterThan(String value) {
            addCriterion("attendtext >", value, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextGreaterThanOrEqualTo(String value) {
            addCriterion("attendtext >=", value, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextLessThan(String value) {
            addCriterion("attendtext <", value, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextLessThanOrEqualTo(String value) {
            addCriterion("attendtext <=", value, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextLike(String value) {
            addCriterion("attendtext like", value, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextNotLike(String value) {
            addCriterion("attendtext not like", value, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextIn(List<String> values) {
            addCriterion("attendtext in", values, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextNotIn(List<String> values) {
            addCriterion("attendtext not in", values, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextBetween(String value1, String value2) {
            addCriterion("attendtext between", value1, value2, "attendtext");
            return (Criteria) this;
        }

        public Criteria andAttendtextNotBetween(String value1, String value2) {
            addCriterion("attendtext not between", value1, value2, "attendtext");
            return (Criteria) this;
        }

        public Criteria andNoticeIsNull() {
            addCriterion("notice is null");
            return (Criteria) this;
        }

        public Criteria andNoticeIsNotNull() {
            addCriterion("notice is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeEqualTo(String value) {
            addCriterion("notice =", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeNotEqualTo(String value) {
            addCriterion("notice <>", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeGreaterThan(String value) {
            addCriterion("notice >", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeGreaterThanOrEqualTo(String value) {
            addCriterion("notice >=", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeLessThan(String value) {
            addCriterion("notice <", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeLessThanOrEqualTo(String value) {
            addCriterion("notice <=", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeLike(String value) {
            addCriterion("notice like", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeNotLike(String value) {
            addCriterion("notice not like", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeIn(List<String> values) {
            addCriterion("notice in", values, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeNotIn(List<String> values) {
            addCriterion("notice not in", values, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeBetween(String value1, String value2) {
            addCriterion("notice between", value1, value2, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeNotBetween(String value1, String value2) {
            addCriterion("notice not between", value1, value2, "notice");
            return (Criteria) this;
        }

        public Criteria andSeqIsNull() {
            addCriterion("seq is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("seq is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(Integer value) {
            addCriterion("seq =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(Integer value) {
            addCriterion("seq <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(Integer value) {
            addCriterion("seq >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("seq >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(Integer value) {
            addCriterion("seq <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(Integer value) {
            addCriterion("seq <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<Integer> values) {
            addCriterion("seq in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<Integer> values) {
            addCriterion("seq not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(Integer value1, Integer value2) {
            addCriterion("seq between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("seq not between", value1, value2, "seq");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_booklist
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 18 14:12:28 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}