package com.landleaf.ibsaas.client.meeting.model.po.meeting.mbg;

import java.io.Serializable;

public class BookCategories implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.id
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.catname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String catname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.orderid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.cattype
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String cattype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.allowroles
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String allowroles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.isdelete
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.url
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.username
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.password
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.domain
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.hasprojector
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String hasprojector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.haspc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String haspc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.hastc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String hastc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.hasvtc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String hasvtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.num
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.numtext
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String numtext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.flash
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String flash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.prev1
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String prev1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.prev2
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String prev2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.ip
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_categories.areaid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.id
     *
     * @return the value of book_categories.id
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.id
     *
     * @param id the value for book_categories.id
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.catname
     *
     * @return the value of book_categories.catname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getCatname() {
        return catname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.catname
     *
     * @param catname the value for book_categories.catname
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setCatname(String catname) {
        this.catname = catname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.orderid
     *
     * @return the value of book_categories.orderid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.orderid
     *
     * @param orderid the value for book_categories.orderid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.cattype
     *
     * @return the value of book_categories.cattype
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getCattype() {
        return cattype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.cattype
     *
     * @param cattype the value for book_categories.cattype
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setCattype(String cattype) {
        this.cattype = cattype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.allowroles
     *
     * @return the value of book_categories.allowroles
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getAllowroles() {
        return allowroles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.allowroles
     *
     * @param allowroles the value for book_categories.allowroles
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setAllowroles(String allowroles) {
        this.allowroles = allowroles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.isdelete
     *
     * @return the value of book_categories.isdelete
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.isdelete
     *
     * @param isdelete the value for book_categories.isdelete
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.url
     *
     * @return the value of book_categories.url
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.url
     *
     * @param url the value for book_categories.url
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.username
     *
     * @return the value of book_categories.username
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.username
     *
     * @param username the value for book_categories.username
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.password
     *
     * @return the value of book_categories.password
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.password
     *
     * @param password the value for book_categories.password
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.domain
     *
     * @return the value of book_categories.domain
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.domain
     *
     * @param domain the value for book_categories.domain
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.hasprojector
     *
     * @return the value of book_categories.hasprojector
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getHasprojector() {
        return hasprojector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.hasprojector
     *
     * @param hasprojector the value for book_categories.hasprojector
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setHasprojector(String hasprojector) {
        this.hasprojector = hasprojector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.haspc
     *
     * @return the value of book_categories.haspc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getHaspc() {
        return haspc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.haspc
     *
     * @param haspc the value for book_categories.haspc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setHaspc(String haspc) {
        this.haspc = haspc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.hastc
     *
     * @return the value of book_categories.hastc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getHastc() {
        return hastc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.hastc
     *
     * @param hastc the value for book_categories.hastc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setHastc(String hastc) {
        this.hastc = hastc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.hasvtc
     *
     * @return the value of book_categories.hasvtc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getHasvtc() {
        return hasvtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.hasvtc
     *
     * @param hasvtc the value for book_categories.hasvtc
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setHasvtc(String hasvtc) {
        this.hasvtc = hasvtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.num
     *
     * @return the value of book_categories.num
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.num
     *
     * @param num the value for book_categories.num
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.numtext
     *
     * @return the value of book_categories.numtext
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getNumtext() {
        return numtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.numtext
     *
     * @param numtext the value for book_categories.numtext
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setNumtext(String numtext) {
        this.numtext = numtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.flash
     *
     * @return the value of book_categories.flash
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getFlash() {
        return flash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.flash
     *
     * @param flash the value for book_categories.flash
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setFlash(String flash) {
        this.flash = flash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.prev1
     *
     * @return the value of book_categories.prev1
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getPrev1() {
        return prev1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.prev1
     *
     * @param prev1 the value for book_categories.prev1
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setPrev1(String prev1) {
        this.prev1 = prev1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.prev2
     *
     * @return the value of book_categories.prev2
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getPrev2() {
        return prev2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.prev2
     *
     * @param prev2 the value for book_categories.prev2
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setPrev2(String prev2) {
        this.prev2 = prev2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.ip
     *
     * @return the value of book_categories.ip
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.ip
     *
     * @param ip the value for book_categories.ip
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_categories.areaid
     *
     * @return the value of book_categories.areaid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_categories.areaid
     *
     * @param areaid the value for book_categories.areaid
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_categories
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", catname=").append(catname);
        sb.append(", orderid=").append(orderid);
        sb.append(", cattype=").append(cattype);
        sb.append(", allowroles=").append(allowroles);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", url=").append(url);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", domain=").append(domain);
        sb.append(", hasprojector=").append(hasprojector);
        sb.append(", haspc=").append(haspc);
        sb.append(", hastc=").append(hastc);
        sb.append(", hasvtc=").append(hasvtc);
        sb.append(", num=").append(num);
        sb.append(", numtext=").append(numtext);
        sb.append(", flash=").append(flash);
        sb.append(", prev1=").append(prev1);
        sb.append(", prev2=").append(prev2);
        sb.append(", ip=").append(ip);
        sb.append(", areaid=").append(areaid);
        sb.append("]");
        return sb.toString();
    }
}