package com.landleaf.ibsaas.client.meeting.dal.dao.meeting.mbg;

import com.landleaf.ibsaas.client.meeting.model.po.meeting.mbg.BookBooklist;
import com.landleaf.ibsaas.client.meeting.model.po.meeting.mbg.BookBooklistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookBooklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    int countByExample(BookBooklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    int deleteByExample(BookBooklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    int insert(BookBooklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    int insertSelective(BookBooklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    List<BookBooklist> selectByExample(BookBooklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    BookBooklist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") BookBooklist record, @Param("example") BookBooklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    int updateByExample(@Param("record") BookBooklist record, @Param("example") BookBooklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    int updateByPrimaryKeySelective(BookBooklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_booklist
     *
     * @mbggenerated Wed Dec 18 14:12:28 CST 2019
     */
    int updateByPrimaryKey(BookBooklist record);
}