package com.landleaf.ibsaas.client.meeting.dal.dao.meeting.mbg;

import com.landleaf.ibsaas.client.meeting.model.po.meeting.mbg.Mac;
import com.landleaf.ibsaas.client.meeting.model.po.meeting.mbg.MacExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MacMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Mac
     *
     * @mbggenerated Tue Dec 17 16:25:25 GMT+08:00 2019
     */
    int countByExample(MacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Mac
     *
     * @mbggenerated Tue Dec 17 16:25:25 GMT+08:00 2019
     */
    int deleteByExample(MacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Mac
     *
     * @mbggenerated Tue Dec 17 16:25:25 GMT+08:00 2019
     */
    int insert(Mac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Mac
     *
     * @mbggenerated Tue Dec 17 16:25:25 GMT+08:00 2019
     */
    int insertSelective(Mac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Mac
     *
     * @mbggenerated Tue Dec 17 16:25:25 GMT+08:00 2019
     */
    List<Mac> selectByExample(MacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Mac
     *
     * @mbggenerated Tue Dec 17 16:25:25 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Mac record, @Param("example") MacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Mac
     *
     * @mbggenerated Tue Dec 17 16:25:25 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Mac record, @Param("example") MacExample example);
}