spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

debug: false
logging:
  config: classpath:logback.xml

web:
  localPath: D:\ibsaas\images\
  picUrl: http://192.168.13.199:8089/images/

#  picUrl: http://192.168.10.181:8089/images/userImages/

