
server:
  port: 9090
  servlet:
    context-path: /client-hvac
    tomcat:
      uri-encoding: UTF-8

spring:
  freemarker:
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    templateEncoding: UTF-8
    template-loader-path: classpath:/templates/
    expose-spring-macro-helpers: false
    static-locations: classpath:/templates/,classpath:/static/
  mvc:
    static-path-pattern: /static/**

ibsaas:
#  face:
#    redirecturl: http://40.73.246.184
  filter:
    cors:
      enable: true
  swagger:
    enable: true
    title: 日志服务
    description: 微服务之 ID 生成服务，仅用于 ID 生成
    version: 1.0
    contactName:
    paths: [/generator]
  dynamic:
    datasource:
      enable: true
      defaultDatasourceName: master
      datasourceList:
        - name: master
          url: jdbc:mysql://40.73.246.184:3306/ibsaas_test?characterEncoding=UTF-8
          username: root
          password: Landleaf@2019
          driverClassName: com.mysql.jdbc.Driver
          maxActive: 50
          initialSize: 5
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
        #       maxWait: 60000
        #       minIdle: 1
        #       timeBetweenEvictionRunsMillis: 60000
        #       minEvictableIdleTimeMillis: 300000
        #       spring.datasource.filters: stat
        - name: slave
          url: jdbc:mysql://40.73.246.184:3306/ibsaas_test?characterEncoding=UTF-8
          username: root
          password: Landleaf@2019
          driverClassName: com.mysql.jdbc.Driver
          maxActive: 50
          initialSize: 5
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
#       maxWait: 60000
#       minIdle: 1
#       timeBetweenEvictionRunsMillis: 60000
#       minEvictableIdleTimeMillis: 300000
#       spring.datasource.filters: stat


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql

id:
  generate:
    workId: 1
    datacenterId: 1
### 个性化配置
##本地设备id
bacnet:
  local:
    deviceId: 1234
