// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMsgProto.proto

package com.landleaf.ibsaas.common.domain.parking.proto;

public final class BaseMsgProto {
  private BaseMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string createTime = 1;</code>
     */
    String getCreateTime();
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string createTime = 1;</code>
     */
    com.google.protobuf.ByteString
        getCreateTimeBytes();

    /**
     * <pre>
     *消息源头
     * </pre>
     *
     * <code>string from = 2;</code>
     */
    String getFrom();
    /**
     * <pre>
     *消息源头
     * </pre>
     *
     * <code>string from = 2;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <pre>
     *消息目的地
     * </pre>
     *
     * <code>string to = 3;</code>
     */
    String getTo();
    /**
     * <pre>
     *消息目的地
     * </pre>
     *
     * <code>string to = 3;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     *消息编号
     * </pre>
     *
     * <code>string msgId = 4;</code>
     */
    String getMsgId();
    /**
     * <pre>
     *消息编号
     * </pre>
     *
     * <code>string msgId = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <pre>
     *消息名称
     * </pre>
     *
     * <code>string msgName = 5;</code>
     */
    String getMsgName();
    /**
     * <pre>
     *消息名称
     * </pre>
     *
     * <code>string msgName = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgNameBytes();

    /**
     * <pre>
     *子消息名称
     * </pre>
     *
     * <code>string subMsgName = 6;</code>
     */
    String getSubMsgName();
    /**
     * <pre>
     *子消息名称
     * </pre>
     *
     * <code>string subMsgName = 6;</code>
     */
    com.google.protobuf.ByteString
        getSubMsgNameBytes();
  }
  /**
   * <pre>
   *公共参数
   * </pre>
   *
   * Protobuf type {@code BaseMsg}
   */
  public  static final class BaseMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseMsg)
      BaseMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseMsg.newBuilder() to construct.
    private BaseMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMsg() {
      createTime_ = "";
      from_ = "";
      to_ = "";
      msgId_ = "";
      msgName_ = "";
      subMsgName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              createTime_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              msgName_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              subMsgName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseMsgProto.internal_static_BaseMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseMsgProto.internal_static_BaseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseMsgProto.BaseMsg.class, BaseMsgProto.BaseMsg.Builder.class);
    }

    public static final int CREATETIME_FIELD_NUMBER = 1;
    private volatile Object createTime_;
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string createTime = 1;</code>
     */
    public String getCreateTime() {
      Object ref = createTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string createTime = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      Object ref = createTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private volatile Object from_;
    /**
     * <pre>
     *消息源头
     * </pre>
     *
     * <code>string from = 2;</code>
     */
    public String getFrom() {
      Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息源头
     * </pre>
     *
     * <code>string from = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 3;
    private volatile Object to_;
    /**
     * <pre>
     *消息目的地
     * </pre>
     *
     * <code>string to = 3;</code>
     */
    public String getTo() {
      Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息目的地
     * </pre>
     *
     * <code>string to = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGID_FIELD_NUMBER = 4;
    private volatile Object msgId_;
    /**
     * <pre>
     *消息编号
     * </pre>
     *
     * <code>string msgId = 4;</code>
     */
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息编号
     * </pre>
     *
     * <code>string msgId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGNAME_FIELD_NUMBER = 5;
    private volatile Object msgName_;
    /**
     * <pre>
     *消息名称
     * </pre>
     *
     * <code>string msgName = 5;</code>
     */
    public String getMsgName() {
      Object ref = msgName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息名称
     * </pre>
     *
     * <code>string msgName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgNameBytes() {
      Object ref = msgName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBMSGNAME_FIELD_NUMBER = 6;
    private volatile Object subMsgName_;
    /**
     * <pre>
     *子消息名称
     * </pre>
     *
     * <code>string subMsgName = 6;</code>
     */
    public String getSubMsgName() {
      Object ref = subMsgName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subMsgName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *子消息名称
     * </pre>
     *
     * <code>string subMsgName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSubMsgNameBytes() {
      Object ref = subMsgName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subMsgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCreateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, createTime_);
      }
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, from_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msgId_);
      }
      if (!getMsgNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgName_);
      }
      if (!getSubMsgNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, subMsgName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCreateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, createTime_);
      }
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, from_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
      }
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msgId_);
      }
      if (!getMsgNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgName_);
      }
      if (!getSubMsgNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, subMsgName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BaseMsgProto.BaseMsg)) {
        return super.equals(obj);
      }
      BaseMsgProto.BaseMsg other = (BaseMsgProto.BaseMsg) obj;

      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
      if (!getFrom()
          .equals(other.getFrom())) return false;
      if (!getTo()
          .equals(other.getTo())) return false;
      if (!getMsgId()
          .equals(other.getMsgId())) return false;
      if (!getMsgName()
          .equals(other.getMsgName())) return false;
      if (!getSubMsgName()
          .equals(other.getSubMsgName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (37 * hash) + MSGNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMsgName().hashCode();
      hash = (37 * hash) + SUBMSGNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSubMsgName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BaseMsgProto.BaseMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BaseMsgProto.BaseMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BaseMsgProto.BaseMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *公共参数
     * </pre>
     *
     * Protobuf type {@code BaseMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseMsg)
        BaseMsgProto.BaseMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseMsgProto.internal_static_BaseMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseMsgProto.internal_static_BaseMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseMsgProto.BaseMsg.class, BaseMsgProto.BaseMsg.Builder.class);
      }

      // Construct using BaseMsgProto.BaseMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        createTime_ = "";

        from_ = "";

        to_ = "";

        msgId_ = "";

        msgName_ = "";

        subMsgName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseMsgProto.internal_static_BaseMsg_descriptor;
      }

      @Override
      public BaseMsgProto.BaseMsg getDefaultInstanceForType() {
        return BaseMsgProto.BaseMsg.getDefaultInstance();
      }

      @Override
      public BaseMsgProto.BaseMsg build() {
        BaseMsgProto.BaseMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BaseMsgProto.BaseMsg buildPartial() {
        BaseMsgProto.BaseMsg result = new BaseMsgProto.BaseMsg(this);
        result.createTime_ = createTime_;
        result.from_ = from_;
        result.to_ = to_;
        result.msgId_ = msgId_;
        result.msgName_ = msgName_;
        result.subMsgName_ = subMsgName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseMsgProto.BaseMsg) {
          return mergeFrom((BaseMsgProto.BaseMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseMsgProto.BaseMsg other) {
        if (other == BaseMsgProto.BaseMsg.getDefaultInstance()) return this;
        if (!other.getCreateTime().isEmpty()) {
          createTime_ = other.createTime_;
          onChanged();
        }
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        if (!other.getMsgName().isEmpty()) {
          msgName_ = other.msgName_;
          onChanged();
        }
        if (!other.getSubMsgName().isEmpty()) {
          subMsgName_ = other.subMsgName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseMsgProto.BaseMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseMsgProto.BaseMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object createTime_ = "";
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 1;</code>
       */
      public String getCreateTime() {
        Object ref = createTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          createTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCreateTimeBytes() {
        Object ref = createTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          createTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 1;</code>
       */
      public Builder setCreateTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 1;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = getDefaultInstance().getCreateTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 1;</code>
       */
      public Builder setCreateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createTime_ = value;
        onChanged();
        return this;
      }

      private Object from_ = "";
      /**
       * <pre>
       *消息源头
       * </pre>
       *
       * <code>string from = 2;</code>
       */
      public String getFrom() {
        Object ref = from_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息源头
       * </pre>
       *
       * <code>string from = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息源头
       * </pre>
       *
       * <code>string from = 2;</code>
       */
      public Builder setFrom(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息源头
       * </pre>
       *
       * <code>string from = 2;</code>
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息源头
       * </pre>
       *
       * <code>string from = 2;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private Object to_ = "";
      /**
       * <pre>
       *消息目的地
       * </pre>
       *
       * <code>string to = 3;</code>
       */
      public String getTo() {
        Object ref = to_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息目的地
       * </pre>
       *
       * <code>string to = 3;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息目的地
       * </pre>
       *
       * <code>string to = 3;</code>
       */
      public Builder setTo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息目的地
       * </pre>
       *
       * <code>string to = 3;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息目的地
       * </pre>
       *
       * <code>string to = 3;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private Object msgId_ = "";
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgId = 4;</code>
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgId = 4;</code>
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgId = 4;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgId = 4;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }

      private Object msgName_ = "";
      /**
       * <pre>
       *消息名称
       * </pre>
       *
       * <code>string msgName = 5;</code>
       */
      public String getMsgName() {
        Object ref = msgName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息名称
       * </pre>
       *
       * <code>string msgName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgNameBytes() {
        Object ref = msgName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息名称
       * </pre>
       *
       * <code>string msgName = 5;</code>
       */
      public Builder setMsgName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息名称
       * </pre>
       *
       * <code>string msgName = 5;</code>
       */
      public Builder clearMsgName() {
        
        msgName_ = getDefaultInstance().getMsgName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息名称
       * </pre>
       *
       * <code>string msgName = 5;</code>
       */
      public Builder setMsgNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgName_ = value;
        onChanged();
        return this;
      }

      private Object subMsgName_ = "";
      /**
       * <pre>
       *子消息名称
       * </pre>
       *
       * <code>string subMsgName = 6;</code>
       */
      public String getSubMsgName() {
        Object ref = subMsgName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          subMsgName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *子消息名称
       * </pre>
       *
       * <code>string subMsgName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSubMsgNameBytes() {
        Object ref = subMsgName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          subMsgName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *子消息名称
       * </pre>
       *
       * <code>string subMsgName = 6;</code>
       */
      public Builder setSubMsgName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subMsgName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *子消息名称
       * </pre>
       *
       * <code>string subMsgName = 6;</code>
       */
      public Builder clearSubMsgName() {
        
        subMsgName_ = getDefaultInstance().getSubMsgName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *子消息名称
       * </pre>
       *
       * <code>string subMsgName = 6;</code>
       */
      public Builder setSubMsgNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subMsgName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BaseMsg)
    }

    // @@protoc_insertion_point(class_scope:BaseMsg)
    private static final BaseMsgProto.BaseMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BaseMsgProto.BaseMsg();
    }

    public static BaseMsgProto.BaseMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMsg>
        PARSER = new com.google.protobuf.AbstractParser<BaseMsg>() {
      @Override
      public BaseMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BaseMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public BaseMsgProto.BaseMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022BaseMsgProto.proto\"k\n\007BaseMsg\022\022\n\ncreat" +
      "eTime\030\001 \001(\t\022\014\n\004from\030\002 \001(\t\022\n\n\002to\030\003 \001(\t\022\r\n" +
      "\005msgId\030\004 \001(\t\022\017\n\007msgName\030\005 \001(\t\022\022\n\nsubMsgN" +
      "ame\030\006 \001(\tB \n\020com.google.protoB\014BaseMsgPr" +
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BaseMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseMsg_descriptor,
        new String[] { "CreateTime", "From", "To", "MsgId", "MsgName", "SubMsgName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
